language: csharp
mono: latest
dotnet: 2.0.3
solution: QuickbooksSync.sln
install:
  - dotnet restore
script:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - dotnet build -c Release --no-restore 
  - dotnet test -c Release --no-build